import Head from 'next/head';
import { Header } from '../components/header';
import { AboutUs } from '../components/about-us';
import { HowWeWork } from '../components/how-we-work/component';
import { Reviews } from '../components/reviews';
import { Footer } from '../components/footer';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>MG Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link href="http://fonts.cdnfonts.com/css/rubik" rel="stylesheet" />
      </Head>
      <Header />
      <AboutUs />
      <HowWeWork />
      <Reviews />
      <Footer />
    </div>
  );
}
